name: CVE scanner
on:
  push:
  pull_request:

concurrency:
  group: cve-scan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      PIP_CACHE_DIR: ~/.cache/pip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Get date
        id: get-date
        run: |
          echo "date=$(date -u +%Y%m%d)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache cve-bin-tool database
        uses: actions/cache@v4
        with:
          path: ~/.cache/cve-bin-tool
          key: Linux-cve-bin-tool-${{ steps.get-date.outputs.date }}
          restore-keys: |
            Linux-cve-bin-tool-

      - name: Install CVE Binary Tool
        run: |
          python -m pip install --upgrade pip
          # Use main branch for latest features; use `pip install cve-bin-tool` to pin PyPI release.
          pip install --no-cache-dir git+https://github.com/intel/cve-bin-tool@main

      - name: Build package if present
        id: build
        run: |
          set -e
          BUILT=0
          if [ -f setup.py ]; then
            echo "Found setup.py — building wheel with setup.py"
            python -m pip install --upgrade wheel setuptools
            python setup.py bdist_wheel
            BUILT=1
          elif [ -f pyproject.toml ]; then
            echo "Found pyproject.toml — building wheel with PEP 517 build"
            python -m pip install --upgrade build
            python -m build --wheel
            BUILT=1
          else
            echo "No setup.py or pyproject.toml found — skipping build step"
          fi
          echo "built=$BUILT" >> $GITHUB_OUTPUT
        shell: bash

      - name: Scan built artifact or repository
        run: |
          # Prefer scanning built artifacts if present; otherwise scan repository tree.
          if [ "${{ steps.build.outputs.built }}" = "1" ] && [ -d dist ]; then
            echo "Scanning dist/ for built packages"
            cve-bin-tool dist -f html -o cve-bin-tool-report.html -x || true
          else
            echo "No built artifacts found — scanning repository files"
            # Scan common locations (repo root). Adjust paths if you only want to scan certain directories.
            cve-bin-tool . -f html -o cve-bin-tool-report.html -x || true
          fi
        continue-on-error: true
        shell: bash

      - name: Upload report as an artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cve_report
          path: cve-bin-tool-report.html
