name: CVE scanner
on:
  push:
  pull_request:

concurrency:
  group: cve-scan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      PIP_CACHE_DIR: ~/.cache/pip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Get date
        id: get-date
        run: |
          echo "date=$(date -u +%Y%m%d)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache cve-bin-tool database
        # cve-bin-tool stores its DB under ~/.cache/cve-bin-tool by default
        uses: actions/cache@v4
        with:
          path: ~/.cache/cve-bin-tool
          key: Linux-cve-bin-tool-${{ steps.get-date.outputs.date }}
          restore-keys: |
            Linux-cve-bin-tool-

      - name: Install CVE Binary Tool
        run: |
          python -m pip install --upgrade pip
          # Use main branch for latest features; swap to `pip install cve-bin-tool`
          # if you prefer the published PyPI version.
          pip install --no-cache-dir git+https://github.com/intel/cve-bin-tool@main

      - name: Build package
        # Replace this with your actual build steps if different.
        run: |
          python -m pip install --upgrade wheel setuptools
          python setup.py bdist_wheel

      - name: Scan built package
        # The tool may exit with a non-zero code when CVEs are found; keep job from failing.
        # Use "|| true" as a safety in case continue-on-error isn't enough in some runners.
        run: |
          if [ -d dist ]; then
            cve-bin-tool dist -f html -o cve-bin-tool-report.html -x || true
          else
            echo "No dist directory found, skipping scan."
          fi
        continue-on-error: true

      - name: Upload report as an artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cve_report
          path: cve-bin-tool-report.html
